### ISSUE TITLE
No messages in Graylog / Empty dashboard

### ISSUE THREAD

**Issue by sirEgghead** [Bsmith101/OPNsense-Dashboard#52]
I'm not seeing anything in Graylog.
![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/6648625/482d06c9-de7d-4374-a49a-c30025f58da1)

Yet I see UDP traffic on 1514 going to my docker container.
![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/6648625/35e6d706-06a4-483e-8f85-f3a908625d30)

The index also shows plenty of messages inbound.
![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/6648625/bbca2a77-0468-44d6-9c62-42e34940293e)

One thing that I noticed during setup is that stream rule processor is missing.  I found documentation that this was forked out of the message filter chain in release 5.0.  I have not yet updated Graylog to 5.0.
![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/6648625/8a9079d1-8d5c-4360-892b-26e840e59185)

If samples of other configuration is needed, I will be happy to provide them.  I did not yet do so because I feel that the relevance is here within Graylog since I see traffic making it past the edge firewall on my docker host and there is evidence of the messages making it to the container.

**Comment by PaulePils** [comment]
I know this thread is closed but I have the same issue. I see querys in Graylog and got data for WAN, LAN, temp, load..... buuut nothing for the firewall logs
<img width="1874" alt="2023-10-12 22_50_55-OPNsense - Dashboards - Dashboards - Grafana – Mozilla Firefox" src="https://github.com/bsmithio/OPNsense-Dashboard/assets/134231607/360020ac-3aa5-4c74-898b-c0b7e6a17c5d">

**Comment by tismofied** [comment]
> I know this thread is closed but I have the same issue. I see querys in Graylog and got data for WAN, LAN, temp, load..... buuut nothing for the firewall logs <img alt="2023-10-12 22_50_55-OPNsense - Dashboards - Dashboards - Grafana – Mozilla Firefox" width="1874" src="https://private-user-images.githubusercontent.com/134231607/274729231-360020ac-3aa5-4c74-898b-c0b7e6a17c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDc3OTUsIm5iZiI6MTcyMTkwNzQ5NSwicGF0aCI6Ii8xMzQyMzE2MDcvMjc0NzI5MjMxLTM2MDAyMGFjLTNhYTUtNGM3NC04OThiLWMwYjdlNmExN2M1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMTM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzQ5N2VjMTFlZmIxZTRkZGQyYmE0Yzk4MjA1N2MyZjhkNjcxMWEyM2JiMDI3OWQ4ZWJmMmQxNzEwYjUxOTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gChHW9GB9egwA81EG9oV42Zv3-3t4S0FlT_LSgDXRms">

I know this is an old thread and I am at this for a week now. Everything checks out except for the firewall. Did you manage to get this fixed by any chance?
