### ISSUE TITLE
issue with setting up greylog.

### ISSUE THREAD

**Issue by dicepvp** [Bsmith101/OPNsense-Dashboard#58]
i followed the steps all the way to where i setup greylog geolocation. when i run the command to download the file with the key i get a error I've tried a few things but I'm not sure what exactly is causing it. i thought maybe something to do with maxmind no longer using legacy keys?. i verified my key works by downloading a config though my browser. please let me know if anyone has any ideas. i google the error and found nothing helpful.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by tismofied** [comment]
darn, I saw your post and was hoping you found a solution. lol
anybody that's running this dashboard have any ideas?

**Comment by dicepvp** [comment]
I did find the solution. You go to the download link and use insect element under network tab if I remember correctly for the direct download link. Then use that instead of the normal download provided the command does not work with redirected links
