### ISSUE TITLE
Unable to download GeoIP database file on Greylog container

### ISSUE THREAD

**Issue by tismofied** [Bsmith101/OPNsense-Dashboard#71]
I followed every step up until I had to run this cmd 
`curl "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=I_PUT_MY_LISENCE_KEY_HERE&suffix=tar.gz" -o GeoLite2-Country.tar.gz \
&& tar -xzvf GeoLite2-Country.tar.gz \
&& mv GeoLite2-Country_*/GeoLite2-Country.mmdb /usr/share/graylog/data/data/`

to download GeoIP database file on Greylog container then I keep getting this error

`gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now`
Anybody got any ideas please???

**Comment by tismofied** [comment]
Shameful bump

**Comment by rp1783** [comment]
I'm getting the same thing. Nothing seems to actually be downloading as the resulting file is 0 bytes.

**Comment by tismofied** [comment]
Exactly the same

**Comment by BeeTwenty** [comment]
i downloaded from the site it self on my local machine and used ftp to transfer it

**Comment by tismofied** [comment]
> i downloaded from the site it self on my local machine and used ftp to transfer it

Where do I Place the file?

**Comment by tismofied** [comment]
![Screenshot 2024-07-23 220827](https://github.com/user-attachments/assets/e90fa899-305f-4277-8c2e-56959433a798)
![Screenshot 2024-07-23 220952](https://github.com/user-attachments/assets/f8917839-0970-4257-b225-6f05e4694d00)

I managed to get theGeolite2 database downloaded but I am having a hard time extracting the downloaded file to it's location
I don't know what to do from here.

**Comment by BeeTwenty** [comment]
> ![Screenshot 2024-07-23 220827](https://github.com/user-attachments/assets/e90fa899-305f-4277-8c2e-56959433a798)
> ![Screenshot 2024-07-23 220952](https://github.com/user-attachments/assets/f8917839-0970-4257-b225-6f05e4694d00)
> 
> I managed to get theGeolite2 database downloaded but I am having a hard time extracting the downloaded file to it's location
> I don't know what to do from here.

What I did is i downloaded it locally and extracted the file. Then transfered it to my docker host and copied it into the containers correct location

**Comment by tismofied** [comment]
> > ![Screenshot 2024-07-23 220827](https://private-user-images.githubusercontent.com/90809124/351550819-e90fa899-305f-4277-8c2e-56959433a798.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjEwNTgsIm5iZiI6MTcyMTg2MDc1OCwicGF0aCI6Ii85MDgwOTEyNC8zNTE1NTA4MTktZTkwZmE4OTktMzA1Zi00Mjc3LThjMmUtNTY5NTk0MzNhNzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDIyMzkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MWJlZTVkYjQ2YjI5MDMzMTdlZmI1NGVhZWM5NjdiZjlhMjBmNmQ5MTU5NjM1NDgxYThmMWViZDY2MWIzOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WYvr3_nEV_BdnXHDFVrI8aRpuqhiSsB9wL9R7HONm_s)
> > ![Screenshot 2024-07-23 220952](https://private-user-images.githubusercontent.com/90809124/351550821-f8917839-0970-4257-b225-6f05e4694d00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjEwNTgsIm5iZiI6MTcyMTg2MDc1OCwicGF0aCI6Ii85MDgwOTEyNC8zNTE1NTA4MjEtZjg5MTc4MzktMDk3MC00MjU3LWIyMjUtNmYwNWU0Njk0ZDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDIyMzkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMDJkNWE4YzNhZTRkMzE1MTEzMDAzNTM4Y2ZjMzc1N2IxZWViNzk1NTNiZDI2ZTliN2ZmZDZhNDg1M2E5MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qSoZjWmgZLri2o5zekBirviZyMgC6bBIzY1xokJ7vak)
> > I managed to get theGeolite2 database downloaded but I am having a hard time extracting the downloaded file to it's location
> > I don't know what to do from here.
> 
> What I did is i downloaded it locally and extracted the file. Then transfered it to my docker host and copied it into the containers correct location

Thank you.

**Comment by mmorys** [comment]
Had the same issue, likely caused by some URL redirects. Use `wget` instead of `curl` to solve this:

Replace the command in the configuration instructions with

```shell
wget -O GeoLite2-Country.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY&suffix=tar.gz" \
&& tar -xzvf GeoLite2-Country.tar.gz \
&& mv GeoLite2-Country_*/GeoLite2-Country.mmdb /usr/share/graylog/data/data/
```
