### ISSUE TITLE
Firewall Panel with No Data and no map activity

### ISSUE THREAD

**Issue by tismofied** [Bsmith101/OPNsense-Dashboard#72]
I followed the steps and tested  and retested all steps. Managed to rectify most errors.
All fixes suggested by either @bsmithio or other contributors have been applied and tested but no matter what I do, I can't get the firewall block of the dashboard to show anything.
I even looked over the reddit thread and tried to look for a fix but nothing worked.

![Screenshot 2024-07-25 090354](https://github.com/user-attachments/assets/c6c2ba64-c630-4514-be2e-eb83ca650a20)

In Graylog there is no output for Geoip and the firewall panel shows no data

![Screenshot 2024-07-25 090552](https://github.com/user-attachments/assets/b58895a7-b945-498b-8d37-52d61c779f53)

![Screenshot 2024-07-26 194428](https://github.com/user-attachments/assets/c4a3130e-1816-4dff-93b8-041f4a6bc1b2)
what am I missing?

**Comment by tismofied** [comment]
~I tried everything including nuking the volumes for this compose file and restarting from scratch. I gave up lol.
I had it working about a year ago 100% , the only difference is I switched to fiber 2 months ago and I am running opnsense as passthrough  with ATT Modem.~

I used one of the forks and got things working. 
Hopefully @bsmithio update all the containers to current ones because I think there a lot of breaking changes in recent updates that render this project not working for a lot of people.

**Comment by jtanamera** [comment]
> ~I tried everything including nuking the volumes for this compose file and restarting from scratch. I gave up lol. I had it working about a year ago 100% , the only difference is I switched to fiber 2 months ago and I am running opnsense as passthrough with ATT Modem.~
> 
> I used one of the forks and got things working. Hopefully @bsmithio update all the containers to current ones because I think there a lot of breaking changes in recent updates that render this project not working for a lot of people.

Hi @tismofied , can you please note which fork worked for you?
