### ISSUE TITLE
Issue with Grafana v11.1.0

### ISSUE THREAD

**Issue by kaczmar1243** [Bsmith101/OPNsense-Dashboard#74]
Hi guys,

I managed to build my OPNsense backline with this tutorial but I am currently stuck with getting dashboard up and running.
I can see that all my log aggregators- graylog and InfluxDB are receiving data from my OPNsense firewall and I can see it in Grafana as well:
![image](https://github.com/user-attachments/assets/974a9f0a-a768-4f7f-a015-d17dce68b765)
![image](https://github.com/user-attachments/assets/c5dca2b3-d22c-4a6d-9453-1571839652a3)
![image](https://github.com/user-attachments/assets/6e946b69-9577-496f-b6ef-f9c8a3c98e6d)
![image](https://github.com/user-attachments/assets/cb607688-9963-4ca5-b049-b485ef0dd049)

The most funny thing is if I go inside dashboard-> variables and querry the same thing over the InfluxDB it doesn't show me any values
![image](https://github.com/user-attachments/assets/374f2644-1960-4988-9c7a-b338aff96a75)

Im getting a little bit mad because I don't understand why it just not working...
Grafana is hosted on different host than other things and is not dockerized.

**Comment by kaczmar1243** [comment]
I just made something in meanwhile and made half of my dashboard working:
I changed host querry to constant and made it as name of my firewall and suddenly some things are just pulled and started working.
![image](https://github.com/user-attachments/assets/4aed7347-9445-4e8a-94d3-8d3db0c4293f)

**Comment by tismofied** [comment]
What version grafana are you using?

**Comment by kaczmar1243** [comment]
> What version grafana are you using?

Grafana v11.1.0

**Comment by tismofied** [comment]
> > What version grafana are you using?
> 
> 
> 
> Grafana v11.1.0

I remember having issues when I upgraded the containers from their default version in the compose file. 
As soon as i went back to the versions that the compose file have, everything started working again.
